# Generated by Django 3.2.6 on 2022-06-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('linkedin_link', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('investor', 'investor'), ('entrepreneur', 'entrepreneur'), ('mentor', 'mentor')], default='entrepreneur', max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('bio', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('projects', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('year_of_experience', models.IntegerField(blank=True, default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(default='1234', max_length=200)),
                ('verification_code', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
