# Generated by Django 3.2.6 on 2022-06-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('funds', models.IntegerField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('documents', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20, null=True)),
                ('clicks', models.IntegerField(blank=True, default=1, null=True)),
                ('impressions', models.IntegerField(blank=True, default=1, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
