# Generated by Django 3.2.6 on 2022-06-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_workshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='clicks',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='impressions',
        ),
        migrations.AddField(
            model_name='idea',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.idea')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
